import{S as g,i,a as y}from"./assets/vendor-D0cagnvz.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&r(d)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const n=document.querySelector(".load"),c=document.querySelector(".more"),b=document.querySelector(".button"),m=document.querySelector(".gallery"),u=document.querySelector(".input"),L=new g(".gallery a",{captionDelay:250});let l=1,p=0;b.addEventListener("click",async t=>{t.preventDefault(),l=1,n.classList.remove("hidden"),m.innerHTML="";try{const s=await h();if(p=s.totalHits,s.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}),c.classList.add("hidden");return}f(s.hits),c.classList.remove("hidden")}catch(s){i.error({message:`Error: ${s.message}`,position:"topRight",timeout:3e3})}finally{n.classList.add("hidden"),u.value=""}});c.addEventListener("click",async()=>{if(l>=Math.ceil(p/15)){i.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c.classList.add("hidden");return}l+=1,n.classList.remove("hidden");try{const t=await h();f(t.hits)}catch(t){i.error({message:`Error: ${t.message}`,position:"topRight",timeout:3e3})}finally{n.classList.add("hidden")}});const h=async()=>{if(u.value.trim()==="")throw i.error({message:"Please enter a search query!",position:"topRight",timeout:3e3}),new Error("Search query is empty.");try{return(await y.get("https://pixabay.com/api/",{params:{key:"34921849-da8a609ca2d9d5a3e9034ffad",q:u.value.trim(),image_type:"photo",orientation:"horizontal",safesearch:"true",page:l,per_page:15}})).data}catch(t){throw console.log(t),i.error({message:t.message,position:"topRight",timeout:3e3}),t}},f=t=>{const s=t.map(r=>`
            <li class="item">
                <a href="${r.largeImageURL}">
                    <img alt="${r.tags}" src="${r.webformatURL}" width="360" height="200"/>
                </a>
                <div class="card">
                    <p class="info-item"><b>Likes</b>${r.likes}</p>
                    <p class="info-item"><b>Views</b>${r.views}</p>
                    <p class="info-item"><b>Comments</b>${r.comments}</p>
                    <p class="info-item"><b>Downloads</b>${r.downloads}</p>
                </div>
            </li>`).join("");m.insertAdjacentHTML("beforeend",s),L.refresh();const a=document.querySelector(".gallery .item");if(a){const r=a.getBoundingClientRect().height;window.scrollBy({top:r,behavior:"smooth"})}};
//# sourceMappingURL=index.js.map
