/* empty css                      */import{a as L,S as v,i as f}from"./assets/vendor-DEenWwFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const h=(r,t)=>{const s={key:"34921849-da8a609ca2d9d5a3e9034ffad",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15},i=new URLSearchParams(s).toString();return L.get(`https://pixabay.com/api/?${i}`)},g=r=>`
                <li class="item">
                    <a href="${r.largeImageURL}">
                        <img alt="${r.tags}" src="${r.webformatURL}" width="360" height="200"/>
                    </a>
                    <div class="card"><p class="info-item"><b>Likes</b>${r.likes}</p>
                    <p class="info-item"><b>Views</b>${r.views}</p>
                    <p class="info-item"><b>Comments</b>${r.comments}</p>
                    <p class="info-item"><b>Downloads</b>${r.downloads}</p>
                    </div>
                </li>`,l=document.querySelector(".load"),p=document.querySelector(".form");document.querySelector(".button");const m=document.querySelector(".gallery"),S=document.querySelector(".input"),n=document.querySelector(".btn-more"),y=new v(".gallery a",{captionDelay:250});let a=1,u=0,c="";const w=async r=>{try{if(r.preventDefault(),c=S.value.trim(),c===""){f.error({message:"Field must be filled in.",position:"topRight",timeout:3e3});return}a=1,n.classList.add("hidden"),l.classList.remove("hidden");const{data:t}=await h(c,a);if(t.hits.length===0){m.innerHTML="",f.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}),p.reset();return}u=Math.ceil(t.totalHits/15),u>1&&(n.classList.remove("hidden"),n.addEventListener("click",b));const s=t.hits.map(e=>g(e)).join("");m.innerHTML=s,y.refresh(),l.classList.add("hidden");const i=document.querySelector(".gallery .item");if(i){const e=i.getBoundingClientRect().height;window.scrollBy({top:e,behavior:"smooth"})}}catch(t){console.log(t)}},b=async r=>{try{l.classList.remove("hidden"),a++;const{data:t}=await h(c,a),s=t.hits.map(e=>g(e)).join("");m.insertAdjacentHTML("beforeend",s),y.refresh(),l.classList.add("hidden");const i=document.querySelector(".gallery .item");if(i){const e=i.getBoundingClientRect().height;window.scrollBy({top:e,behavior:"smooth"})}a===u&&(n.classList.add("hidden"),n.removeEventListener("click",b))}catch(t){console.log(t)}};p.addEventListener("submit",w);
//# sourceMappingURL=index.js.map
