import{S as g,i as a,a as y}from"./assets/vendor-D0cagnvz.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&t(d)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();const n=document.querySelector(".load"),c=document.querySelector(".more"),b=document.querySelector(".button"),u=document.querySelector(".gallery"),m=document.querySelector(".input"),L=new g(".gallery a",{captionDelay:250});let l=1,p=0;b.addEventListener("click",async o=>{o.preventDefault(),l=1,n.classList.remove("hidden"),u.innerHTML="";try{const r=await f();if(p=r.totalHits,r.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}),c.classList.add("hidden");return}h(r.hits),c.classList.remove("hidden")}catch(r){a.error({message:`Error: ${r.message}`,position:"topRight",timeout:3e3})}finally{n.classList.add("hidden"),m.value=""}});c.addEventListener("click",async()=>{if(l>=Math.ceil(p/15)){a.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c.classList.add("hidden");return}l+=1,n.classList.remove("hidden");try{const o=await f();h(o.hits)}catch(o){a.error({message:`Error: ${o.message}`,position:"topRight",timeout:3e3})}finally{n.classList.add("hidden")}});const f=async()=>(await y.get("https://pixabay.com/api/",{params:{key:"34921849-da8a609ca2d9d5a3e9034ffad",q:m.value.trim(),image_type:"photo",orientation:"horizontal",safesearch:"true",page:l,per_page:15}})).data,h=o=>{const r=o.map(t=>`
            <li class="item">
                <a href="${t.largeImageURL}">
                    <img alt="${t.tags}" src="${t.webformatURL}" width="360" height="200"/>
                </a>
                <div class="card">
                    <p class="info-item"><b>Likes</b>${t.likes}</p>
                    <p class="info-item"><b>Views</b>${t.views}</p>
                    <p class="info-item"><b>Comments</b>${t.comments}</p>
                    <p class="info-item"><b>Downloads</b>${t.downloads}</p>
                </div>
            </li>`).join("");u.insertAdjacentHTML("beforeend",r),L.refresh();const i=document.querySelector(".gallery .item");if(i){const t=i.getBoundingClientRect().height;window.scrollBy({top:t,behavior:"smooth"})}};
//# sourceMappingURL=index.js.map
